### ISSUE TITLE
Add density measures

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#48] opened 2019-12-01 00:03 UTC
* [x] Log loss
* [ ] Brier score

**Comment by fkiraly** [comment] 2019-12-01 23:41
isn't this a duplication?
https://github.com/mlr-org/mlr3proba/issues/34

**Comment by RaphaelS1** [comment] 2019-12-02 08:06
Possibly. Unsure. It isn't yet clear whether we would need to deliberately duplicate measures as they may require a particular prediction type.

**Comment by fkiraly** [comment] 2019-12-02 11:53
Ah, I see - the prediction type, or even the method by which the distirbution is queried, may be different.

I see how the current design may necessitate separating out the "the log-loss for density estimation" from "the log-loss for proba. supervised regression".

From an architectural modelling standpoint, however, this seems very counterintuitive and strange, as the mathematical objects (the loss function) are the same.

Any good ideas how this could be resolved without major surgery?

**Comment by RaphaelS1** [comment] 2019-12-02 14:39
I actually don't think it's a problem. If you look at how measures are named, e.g. `surv.graf`, `classif.mmce`; then it seems sensible to have `surv.logloss`, `density.logloss`, `regr.logloss`

**Comment by RaphaelS1** [comment] 2019-12-02 14:39
(one can always inherit from the other - efficient although maybe slightly messy)

**Comment by fkiraly** [comment] 2019-12-02 14:56
The conceptual pain that this causes me is that `classif.bla` and `regr.blubb` represent, usually, different mathematical objects. Whereas `density.logloss` and `regr.logloss` would represent the *same* mathematical object - the log-loss for absolutely continuous distributions over the reals. 
The difference is entirely localized in "accessory functionality" in application to the outputs of the estimation strategy, not in the object that it represents, which disturbs me, since it seems to violate an uncodified "same mathematical object, same class" principle.

**Comment by RaphaelS1** [comment] 2019-12-02 17:16
There's no reason why someone can't use `regr.logloss` on `PredictionDensity` as long as they both have the same predict type. But this will just be confusing to the user.

**Closed** 2023-12-08 10:00 UTC
Labels: Priority: Low, Status: Accepted, Status: In Progress, Type: Enhancement
