### ISSUE TITLE
Latest mlr3 updates caused old code does not work for some models 

### ISSUE THREAD

**Issue by aalhadab** [mlr-org/mlr3proba#248] opened 2022-02-11 04:04 UTC
"surv.rfsrc" never had this error before the updates
rfsrc$predict_newdata(dataset)
simpleError in doTryCatch(return(expr), name, parentenv, handler): attempt to set index 6/6 in SET_VECTOR_ELT>
Error in generic.predict.rfsrc(object, newdata, m.target = m.target, importance = importance,  : 
  An error has occurred in prediction.  Please turn trace on for further analysis.

"surv.gbm" during tuning, never had this error before the updates
Error in gbm.fit(x = x, y = y, offset = offset, distribution = distribution,  : 
The data set is too small or the subsampling rate is too large: `nTrain * bag.fraction <= n.minobsinnode`
This happened PipeOp GBM's $train()

**Comment by RaphaelS1** [comment] 2022-02-11 10:25
Hi please produce a reprex or we can't help. There is no way for me to try to reproduce the above error.

However, I recognise both those errors, which are common to their respective packages. The first seems to happen stochastically and just needs a session refresh. The latter shows the problem, your hyperparameters need adjusting

**Comment by aalhadab** [comment] 2022-02-16 16:12
I was able to replicate the error 

``` r
library(mlr3verse)
#> Warning: package 'mlr3verse' was built under R version 4.1.2
#> Loading required package: mlr3
library(tidyverse)
#> Warning: package 'tidyverse' was built under R version 4.1.2
#> Warning: package 'ggplot2' was built under R version 4.1.2
#> Warning: package 'tibble' was built under R version 4.1.2
#> Warning: package 'tidyr' was built under R version 4.1.2
#> Warning: package 'readr' was built under R version 4.1.2
#> Warning: package 'purrr' was built under R version 4.1.2
#> Warning: package 'dplyr' was built under R version 4.1.2
#> Warning: package 'stringr' was built under R version 4.1.2
#> Warning: package 'forcats' was built under R version 4.1.2
library(tidymodels)
#> Warning: package 'tidymodels' was built under R version 4.1.2
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
#> Warning: package 'broom' was built under R version 4.1.2
#> Warning: package 'dials' was built under R version 4.1.2
#> Warning: package 'scales' was built under R version 4.1.2
#> Warning: package 'infer' was built under R version 4.1.2
#> Warning: package 'modeldata' was built under R version 4.1.2
#> Warning: package 'parsnip' was built under R version 4.1.2
#> Warning: package 'recipes' was built under R version 4.1.2
#> Warning: package 'rsample' was built under R version 4.1.2
#> Warning: package 'tune' was built under R version 4.1.2
#> Warning: package 'workflows' was built under R version 4.1.2
#> Warning: package 'workflowsets' was built under R version 4.1.2
#> Warning: package 'yardstick' was built under R version 4.1.2

task = tsk("actg")

set.seed(123)
split <- task$data()  %>% initial_split(strata = status)    
train <- split %>% training()
test  <- split %>% testing()

task2 = TaskSurv$new("ACT_G", backend = train,  time = "time", event = "status")

learner = lrn("surv.rfsrc", na.action = "na.impute", importance = "permute", var.used ="all.trees")

learner$train(task2)

learner$predict_newdata(test)$score(msrs(c("surv.cindex", "surv.graf")))
#> <simpleError in doTryCatch(return(expr), name, parentenv, handler): attempt to set index 5/5 in SET_VECTOR_ELT>
#> Error in generic.predict.rfsrc(object, newdata, m.target = m.target, importance = importance, : An error has occurred in prediction.  Please turn trace on for further analysis.
```

<sup>Created on 2022-02-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by aalhadab** [comment] 2022-02-18 18:34
The repex was created with 
mlr3 0.13.2 
mlr3proba 0.4.3
mlr3extralearners 0.5.24
rfsrc 3.0.1

**Comment by RaphaelS1** [comment] 2022-02-20 09:36
The issue is that `var.used` is passed to both the training and predicting function in rfsrc (as both those functions can take it as a variable):

``` r
library(survival)
library(randomForestSRC)
train = sample(300, 200)
test = setdiff(seq(300), train)
rats = survival::rats
rats$sex = rats$sex == "m"
fit = rfsrc(
  Surv(time, status) ~ ., data = rats[train,], na.action = "na.impute",
  importance = "permute", var.used = "all.trees")
predict(fit, rats[test,], na.action = "na.impute",
  importance = "permute", var.used = "all.trees")
#> <simpleError in doTryCatch(return(expr), name, parentenv, handler): attempt to set index 8/8 in SET_VECTOR_ELT>
#> Error in generic.predict.rfsrc(object, newdata, ensemble = ensemble, m.target = m.target, : An error has occurred in prediction.  Please turn trace on for further analysis.
```

<sup>Created on 2022-02-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This is a strange case because the mlr3 code is doing what is expected except that here the underlying model doesn't expect the same argument to be passed at two different stages. 

As a temporary solution you could turn off `var.used` after training:

``` r
library(mlr3verse)

task = tsk("actg")
task$add_strata("status")

set.seed(123)
split <- partition(task, stratify = TRUE)

learner = lrn("surv.rfsrc", na.action = "na.impute", importance = "permute", var.used = 'all.trees')

learner$train(task, row_ids = split$train)
learner$selected_features()
#>      age      cd4 hemophil   ivdrug   karnof priorzdv   raceth     sexF 
#>     2061     2596      178      502     1403     1702     1104      495 
#>   strat2       tx    txgrp 
#>      483      419      453

learner$param_set$values$var.used = 'FALSE'

learner$predict(task, row_ids = split$test)$score(msrs(c("surv.cindex", "surv.graf")))
#> surv.cindex   surv.graf 
#>  0.79436535  0.05787643
```

<sup>Created on 2022-02-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by RaphaelS1** [comment] 2022-02-20 09:37
@mllg do you think we could enchance parameter setting so in cases like in above where the parameter *could* be passed to training and testing but usually is only used in one, the user can specify which one it is passed to?

Obviously we could split the parameter into two, e.g. `var_used_train` and `var_used_test` but might be more confusing?

**Comment by mllg** [comment] 2022-02-20 09:47
Splitting in two hyperparameters is the way to do it properly. Otherwise it just gets more complex for tuning etc.

**Comment by mllg** [comment] 2022-02-20 09:52
Without having a closer look ... Is `var.used` really a predict-time parameter? You would only set it to calculate the importance, but it has no effect on the prediction?

**Comment by RaphaelS1** [comment] 2022-02-20 16:32
Agreed, which is why I've manually fixed in https://github.com/mlr-org/mlr3extralearners/pull/178 and believe it's just a bug in rfsrc. I think the idea is a user could use it *either* in training *or* testing but not both

**Closed** 2022-02-20 17:30 UTC

**Comment by RaphaelS1** [comment] 2022-02-22 08:09
@aalhadab update to latest version of mlr3extralearners for the fix
